name: Publish androidaap Withkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4


    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Download KeyStore
      run: |
 
       java -version

        curl -o 'AppMareee.keystore'  https://bit.ly/4cdwxvD 
       
         keytool -list -v -keystore 'AppMareee.keystore'  -storepass 20012008 -alias AppMareKeyio -storetype JKS


    - name: Setup Maui
      run: dotnet workload install maui
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="$(pwd)/AppMareee.keystore" -p:AndroidSigningKeyAlias=AppMareKeyio -p:AndroidSigningKeyPass=20012008 -p:AndroidSigningStorePass=20012008
    - name: Find and Copy AAB and APK
      run: |
          mkdir artifacts
          find . -type f \( -name "*Signed*.aab" -o -name "*Signed*.apk" \) -exec cp --parents {} artifacts/ \;
    - name: Upload AAB and APK
      uses: actions/upload-artifact@v3
      with:
          name: app-release
          path: artifacts/
         
  

        
