name: Publish androidapk Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - id: generatedpassword
      uses: Ba4bes/Password-Generator@v0.1
    - run: echo "${{ steps.generatedpassword.outputs.password }}"
      shell: bash
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x


    - name: Setup Maui
      run: dotnet workload install maui
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Get IPA Path
      id: find-ipa
      run: |
 
         echo "ipa-path=$(find $(pwd) -name "*.ipa")"  >> $GITHUB_ENV
         
  

        
