# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish IOS Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Fastlane lane
      env:
        FASTLANE_ISSUER_ID: 'adf9507d-dc61-424e-8c5a-32458ea0b617'
        FASTLANE_KEY_ID: '2ZLY3J6J82'
        FASTLANE_PRIVATE_KEY: 'MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsWI+PNBGEt+dscL/sQqQRMbbmDC9gBQSHBRdGw046HigCgYIKoZIzj0DAQehRANCAATcoDiiH3lmvFzUjnL4w8jzwZ0CiV8S81O5nyFZ6WNZpMclcN+VyLodgkl5I10F5um7k8/VuxLRhNF/Czs53QRL'
    - name: FastLane lane
      run: fastlane match appstore --app_identifier com.companyname.samplemaui --readonly --profile_name MyCustomProfileName --git_url https://github.com/Elkadyy2001/MauiTest.git

    - name: Get Code Signing Key
      id: get_code_signing_key
      run: echo "::set-env name=CODE_SIGNING_KEY::$(security find-identity -p codesigning -v | grep '"' | head -n1 | awk -F '"' '{print $2}')"
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.ipa
    
    
    
      
      
        

