name: Publish IOS Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create NewKeyChain
      run: |
            security create-keychain -p 2001 Build.keychain
            security list-keychains -d user -s login.keychain Build.keychain
            security default-keychain -s Build.keychain
            

      
    - name: Fastlane lane
      env:
        MATCH_PASSWORD: '12345678'
      run: |
       fastlane match appstore --app_identifier com.companyname.samplemaui --profile_name MyCustomProfileName --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch main --keychain_name Build.keychain    --api_key '{
              "filepath": "./AuthKey_2ZLY3J6J82.p8"
              ,"key_id": "2ZLY3J6J82",
              "issuer_id": "adf9507d-dc61-424e-8c5a-32458ea0b617",
              "in_house": false
              
            }'   
    - name: Get Code Signing Key
      id: get_code_signing_key
      run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep '"' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Remove Prompt
      run: |
            security unlock-keychain -p 2001 build.keychain
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k 2001 Build.keychain
    - name: Setup Maui
      run: dotnet workload install maui
   
        
  


    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.ipa
    
    
    
      
      
        

