name: Publish IOS Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
   

            
    
      
    - name: Fastlane lane
      env:
        MATCH_PASSWORD: '12345678'
        MATCH_KEYCHAIN_PASSWORD: '2001'
        MATCH_KEYCHAIN_NAME: 'build.keychain-db'

      run: |
       security create-keychain -p "2001" "build.keychain-db"

    
        security list-keychains -s "build.keychain-db" "~/Library/Keychains/login.keychain-db"
            security default-keychain -s "build.keychain-db"
         fastlane match appstore --app_identifier com.companyname.samplemaui --profile_name MyCustomProfileName --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch main  --api_key '{
              "filepath": "./AuthKey_2ZLY3J6J82.p8"
              ,"key_id": "2ZLY3J6J82",
              "issuer_id": "adf9507d-dc61-424e-8c5a-32458ea0b617",
              "in_house": false
              
            }' 
            bundle exec fastlane run_match_signing
             - name: Get Code Signing Key
              id: get_code_signing_key
               run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep '"' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
       - name: SetupCli
         run: |
         IDENTITY=$(security find-certificate -c "${{ env.CODE_SIGNING_KEY }}" -p | openssl x509 -noout -subject | awk -F'CN=' '{print $2}' | tr -d '"')
       security set-key-partition-list -S apple-tool:,apple: -s -k 2001 ~/Library/Keychains/build.keychain-db
       security set-key-partition-list -S apple-tool:,apple: -s -k 2001 -t private ~/Library/Keychains/build.keychain-db
       security set-key-partition-list -S apple-tool:,apple: -s -k 2001 -t private -D "$IDENTITY" ~/Library/Keychains/build.keychain-db
   

   
    
    - name: Setup Maui
      run: dotnet workload install maui
   
        
  


    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.ipa
    
    
    
      
      
        

