# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish IOS Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Fastlane lane
      env:
        FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
        FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
        FASTLANE_PRIVATE_KEY: ${{ secrets.FASTLANE_PRIVATE_KEY }}
      run: fastlane match appstore
    - name: Archive generated certificates and provisioning profile
      uses: actions/upload-artifact@v2
      with:
          name: certificates_and_profiles
          path: "~/Library/MobileDevice/Provisioning Profiles, ~/.fastlane/certs"
    
    
    
      
      
        

