name: Publish IOS With ScreenShots Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Fastlane lane
      env:
        MATCH_PASSWORD: '12345678'
        MATCH_KEYCHAIN_NAME: 'build.keychain'
        MATCH_KEYCHAIN_PASSWORD: '2001'
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.PATTOKEN }}
      run: |
         security create-keychain -p 2001 build.keychain
         security default-keychain -s build.keychain
         security list-keychains -s build.keychain
         security unlock-keychain -p 2001 build.keychain
         security set-keychain-settings -t 3600 -u build.keychain
         api_key_json=$(jq -n --arg key "${{secrets.APIKEY}}" --arg key_id "${{ secrets.KEYID }}" --arg issuer_id "${{ secrets.ISSUERID }}" '{key: $key, key_id: $key_id, issuer_id: $issuer_id, in_house: false}')
         fastlane match nuke distribution  --skip_confirmation true --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch master  --api_key "$api_key_json"
         fastlane match appstore --app_identifier com.companyname.samplemaui --profile_name MyCustomProfileName --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch master  --api_key "$api_key_json"
    - name: Get Release Code Signing Key
      run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep 'Apple Distribution' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Get Dev Code Signing Key
      run: echo "coddev=$(security find-identity -p codesigning -v | grep 'Apple Development' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:MtouchLink=Full -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Get IPA Path
      run: echo "ipa-path=$(find $(pwd) -name "*.ipa")"  >> $GITHUB_ENV

         
    # - name: Build Debug App
    
    #   run: |
    #    dotnet clean
    #    dotnet restore
    #        dotnet build  -f net8.0-ios -p:CodesignKey="${{ env.coddev }}" -p:CodesignProvision="DebugProfileName" -p:_DeviceName=:v2:udid=$(xctrace list devices | grep -B1 -E "iPhone 15 Pro Max|iPhone 15 Pro" | grep -oE '[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}' | head -n 1)
    - name: Get App Path
      run: echo "app-path=$(find $(pwd)/SampleMaui/bin/Release -name "*.app")"  >> $GITHUB_ENV
   
    - name: Deploy App To simulator
      run: |
             simulators=("iPhone 15 Pro Max" "iPhone 15 Pro" "iPhone SE (3rd generation)" "iPad Pro (12.9-inch) (6th generation)" "iPad (10th generation)")
             for name in "${simulators[@]}"; do
             echo "Booting simulator $name"
             xcrun simctl boot "$name"
             echo "Deploying app"
             xcrun simctl install booted "${{ env.app-path }}"
             xcrun simctl shutdown booted
             done
             fastlane snapshot --project "./FastlaneScreenShot/FastlaneScreenShot.xcodeproj"
       
    - name: Publish To Store
      run: |
       api_key_json=$(jq -n --arg key "${{secrets.APIKEY}}" --arg key_id "${{ secrets.KEYID }}" --arg issuer_id "${{ secrets.ISSUERID }}" '{key: $key, key_id: $key_id, issuer_id: $issuer_id, in_house: false}')
       fastlane deliver --overwrite_screenshots true --ipa "${{ env.ipa-path }}" --api_key "$api_key_json"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ${{ env.ipa-path }}                 

