name: Publish IOS With ScreenShots Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 'latest'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Fastlane lane
      env:
        MATCH_PASSWORD: '12345678'
        MATCH_KEYCHAIN_NAME: 'build.keychain'
        MATCH_KEYCHAIN_PASSWORD: '2001'
        MATCH_GIT_BASIC_AUTHORIZATION: 'RWxrYWR5eTIwMDE6Z2hwXzRxRWpjakJoU2hxMTBxMXlTOG9obEhndmNxMHE4WDJQWHlTQg=='
        token: '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'
      run: |
         security create-keychain -p 2001 build.keychain
         security default-keychain -s build.keychain
         security list-keychains -s build.keychain
         security unlock-keychain -p 2001 build.keychain
         security set-keychain-settings -t 3600 -u build.keychain
         fastlane match nuke distribution  --skip_confirmation true --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch master  --api_key '{
              "filepath": "./AuthKey_2ZLY3J6J82.p8"
              ,"key_id": "2ZLY3J6J82",
              "issuer_id": "adf9507d-dc61-424e-8c5a-32458ea0b617",
              "in_house": false
              
            }' 


         fastlane match appstore --app_identifier com.companyname.samplemaui --profile_name MyCustomProfileName --git_url https://github.com/Elkadyy2001/MauiTest.git --git_branch master  --api_key '{
              "filepath": "./AuthKey_2ZLY3J6J82.p8"
              ,"key_id": "2ZLY3J6J82",
              "issuer_id": "adf9507d-dc61-424e-8c5a-32458ea0b617",
              "in_house": false
              
            }' 
    - name: Get Code Signing Key
      id: get_code_signing_key
      run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep '"' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName"
    - name: Get IPA Path
      id: find-ipa
      run: |
         echo "ipa-path=$(find $(pwd) -name "*.ipa")"  >> $GITHUB_ENV
    - name: Build Debug App
    - run:  dotnet build  -f net8.0-ios 
    - name: Get App
      run: |
         echo "app-path=$(find $(pwd)/bin/Debug -name "*.app")"  >> $GITHUB_ENV
    - name: Deploy App To simulator
    - run: |
             uids=$(xctrace list devices | grep -B1 -E "iPhone 15 Pro Max|iPhone 15 Pro|iPhone SE (3rd generation)|iPad Pro (12.9-inch) (6th generation)|iPad (10th generation)" | grep -oE '[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}')
             for uid in $uids; do
             echo "Booting simulator $uid"
             xcrun simctl boot $uid
             echo "Deploying app"
             xcrun simctl install $uid "${{ env.app-path }}"
             done
             fastlane snapshot --project "./FastlaneScreenShot/FastlaneScreenShot.xcodeproj"
             xcrun simctl shutdown all
    - name: Publish To Store
      run:  dddddddd  
