name: Publish android Play newkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - id: generatedpassword
      uses: Ba4bes/Password-Generator@v0.1
    - name: Setup Project
      run: |
       wget -O "$(pwd)/AppName.zip" "https://bit.ly/45kQ6zr"

       unzip "$(pwd)/AppName.zip" -d $(pwd)
       cd "$(pwd)/AppName"
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Generate KeyStore
      run: |
          cd "$(pwd)/AppName"
          keytool -genkeypair -v -keystore $(pwd)/AppMare.keystore  -keyalg RSA -keysize 2048 -validity 365000 -storepass "${{ steps.generatedpassword.outputs.password }}" -alias ${{ secrets.KEYSTOREALIAS }}" -dname "cn=Appmare"

    - name: Setup Maui
      run: dotnet workload install maui
    - name: Publish App
      run: |
        cd "$(pwd)/AppName"
        dotnet publish -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="$(pwd)/AppMare.keystore" -p:AndroidSigningKeyAlias=${{ secrets.KEYSTOREALIAS }}" -p:AndroidSigningKeyPass="${{ steps.generatedpassword.outputs.password }}" -p:AndroidSigningStorePass="${{ steps.generatedpassword.outputs.password }}"
    - name: Find and Copy AAB and APK
      run: |
          cd "$(pwd)/AppName"
          echo "aab-path=$(find $(pwd)/SampleMaui/bin/Release/net8.0-android/publish -name "*Signed*.aab")"  >> $GITHUB_ENV
          echo "apk-path=$(find $(pwd)/SampleMaui/bin/Release/net8.0-android/publish -name "*Signed*.apk")"  >> $GITHUB_ENV
          echo -e "aliasName:${{ secrets.KEYSTOREALIAS }}" \n KeyStorePassword: "${{ steps.generatedpassword.outputs.password }}" > $(pwd)/KeyStore Credentials.txt 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ${{ env.aab-path }}
           ${{ env.apk-path }}
           $(pwd)/AppMare.keystore
           $(pwd)/KeyStore Credentials.txt 
         
  

        
