name: Publish androidaap Withkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Setup Project
      run: |
       wget -O "$(pwd)/AppName.zip" "https://bit.ly/4b53xon"

       unzip "$(pwd)/AppName.zip" -d $(pwd)
        


    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Download KeyStore
      run: |
       cd "$(pwd)/AppName"
        wget -O "$(pwd)/AppMare.keystore" "${{ secrets.KEYURL }}"
   
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Publish App
      run: |
         cd "$(pwd)/AppName"
         dotnet publish -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="$(pwd)/AppMare.keystore" -p:AndroidSigningKeyAlias="${{ secrets.KEYSTOREALIAS }}" -p:AndroidSigningKeyPass="${{ secrets.KEYSTOREPASS }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTOREPASS }}"
    - name: Find and Copy AAB and APK
      run: |
         
          echo "aab-path=$(find $(pwd)/AppName/SampleMaui/bin/Release/net8.0-android/publish -name "*Signed*.aab")"  >> $GITHUB_ENV
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ${{ env.aab-path }}
           
    - name: Deploy To PlayStore
      uses: r0adkll/upload-google-play@v1
      with:
       serviceAccountJsonPlainText: "${{ secrets.PLAYDATA}}"
       packageName: com.companyname.samplemaui
       releaseFiles: ${{ env.aab-path }}
       track: beta
       
              
  

        
