name: Publish androidaap Withkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4




    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Download KeyStore
      run: |
  
       wget -O "$(pwd)/AppMare.keystore" " ${{ secrets.KEYURL }}"
   
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Restore App
      run: dotnet restore
    - name: Publish App
      run: dotnet publish -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="$(pwd)/AppMare.keystore" -p:AndroidSigningKeyAlias=" ${{ secrets.KEYSTOREALIAS }}" -p:AndroidSigningKeyPass=" ${{ secrets.KEYSTOREPASS }}" -p:AndroidSigningStorePass=" ${{ secrets.KEYSTOREPASS }}"
    
         
  

        
