name: Publish MacToStore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: ruby/setup-ruby@v1
    
      with:
              ruby-version: '3.3'

    - uses: tashi-iu/setup-fastlane@v1
      with:
    # Optional. Default: 'latest'
            version: 2.219.0'
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Project
      run: |
          wget -O "$(pwd)/AppName.zip" "${{ secrets.PROJECTURL }}"

          unzip "$(pwd)/AppName.zip" -d $(pwd)
      
    - name: Fastlane lane
      env:
        MATCH_PASSWORD: '12345678'
        MATCH_KEYCHAIN_NAME: 'build.keychain'
        MATCH_KEYCHAIN_PASSWORD: '2001'
        MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.PAT }}'
       
      run: |
         cd "$(pwd)/AppName"  
         security create-keychain -p 2001 build.keychain
         security default-keychain -s build.keychain
         security list-keychains -s build.keychain
         security unlock-keychain -p 2001 build.keychain
         security set-keychain-settings -t 3600 -u build.keychain
         api_key_json=$(jq -n --arg key "${{secrets.APIKEY}}" --arg key_id "${{ secrets.KEYID }}" --arg issuer_id "${{ secrets.ISSUERID }}" '{key: $key, key_id: $key_id, issuer_id: $issuer_id, in_house: false}')

         fastlane match nuke distribution  --skip_confirmation true --git_url "${{ secrets.GITURL }}" --git_branch master --api_key "$api_key_json"
        


         fastlane match appstore --platform macos --additional_cert_types mac_installer_distribution --app_identifier com.companyname.samplemaui --profile_name MyCustomProfileName --git_url "${{ secrets.GITURL }}" --git_branch master  --api_key "$api_key_json"
            
    - name: Get Code Signing Key
      run: echo "CODE_SIGNING_KEY=$(security find-identity -p codesigning -v | grep 'Apple Distribution' | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Get Package Signing Key
      run: echo "Package_SIGNING_KEY=$(security find-identity -p macappstore -v | grep "3rd Party Mac Developer Installer" | head -n1 | awk -F '"' '{print $2}')" >> $GITHUB_ENV
    - name: Setup Maui
      run: dotnet workload install maui
    - name: Publish App
     
      run: |
          cd "$(pwd)/AppName"  
          dotnet publish -f net8.0-maccatalyst -c Release  -p:CreatePackage=true -p:EnableCodeSigning=true -p:EnablePackageSigning=true -p:CodesignKey="${{ env.CODE_SIGNING_KEY }}" -p:CodesignProvision="MyCustomProfileName" -p:PackageSigningKey="${{ env.Package_SIGNING_KEY }}"
    - name: Get Pkg Path

      run: |
             cd "$(pwd)/AppName"  
             echo "pkg-path=$(find $(pwd) -name "*.pkg")"  >> $GITHUB_ENV
             echo -e "${{secrets.APIKEY}}" > $(pwd)/AuthKey66878.p8
         
    - name: Publish To Store
      env: 
          API_PRIVATE_KEYS_DIR: '$(pwd)'
      run: |
          cd "$(pwd)/AppName"  
          xcrun altool --validate-app -f "${{ env.pkg-path }}" -t osx --apiKey "${{ secrets.KEYID }}"  --apiIssuer "${{ secrets.ISSUERID }}"
          xcrun altool --upload-app -f "${{ env.pkg-path }}" -t osx --apiKey "${{ secrets.KEYID }}"  --apiIssuer "${{ secrets.ISSUERID }}"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ${{ env.pkg-path }}
    
    
      
      
        
