name: Publish Windows Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
 

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Project
      run: |
       Invoke-WebRequest -Uri "https://bit.ly/4b53xon" -OutFile "$(Get-Location)/AppName.zip"


       unzip "$(pwd)/AppName.zip" -d $(pwd)
       cd "$(pwd)/AppName"

    - name: Setup Maui
      run: |
      
         dotnet workload list
         # dotnet workload install maui-windows
    - name: Publish App
      run: |
           cd "$(pwd)/AppName"
           dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true -p:PublishSingleFile=true --self-contained true -p:PublishTrimmed=true -p:TrimMode=partial

    - name: Find and Copy AAB and APK
      run: |
          cd "$(pwd)/AppName"
      
           echo "exe-path=$(find $(pwd)/SampleMaui/bin/Release/net8.0-windows10.0.19041.0 -name "*.exe")"  >> $GITHUB_ENV

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ${{ env.exe-path }}

          

        
